Controller_Test:
  Circle:
    Center_x: 0.0
    Center_y: 0.0
    Center_z: 15.0
    circle_radius: 4.0         ## m   半径越小越难追踪
    linear_vel: 0.3             ## m/s  速度越大越难追踪
    direction: 1.0              ##direction = 1 for CCW 逆时针, direction = -1 for CW 顺时针
  Eight:
    Center_x: 0.0
    Center_y: 0.0
    Center_z: 1.0
    radial: 2.0               ## m   半径越小越难追踪
    omega: 0.3                ## rad/s  角速度越大越难追踪
  Step:
    step_length: 2.0          ## m    长度越大越难追踪
    step_interval: 5.0
flight_track:
  point1:
    point_x: 0.0
    point_y: 0.0
    point_z: 13.0 
    point_yaw: 0.0
  point2:
    point_x: 0.0
    point_y: -3.0
    point_z: 4.0
    point_yaw: 0.0
  point3:
    point_x: -3.0
    point_y: -3.0
    point_z: 4.0
    point_yaw: 0.0
  point4:
    point_x: -3.0
    point_y: 0
    point_z: 4
    point_yaw: 0.0 
  point5:
    point_x: 0
    point_y: 0
    point_z: 4
    point_yaw: 0.0
  point6:
    point_x: 0
    point_y: 0 
    point_z: 4.0
    point_yaw: 0.0
  n: 1
  Kp: 3.0
  Kd: 18.0



